version: '3'
services:
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    networks:
      - demo_deploy

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    networks:
      - demo_deploy

  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - demo_deploy
    depends_on:
      - backend
      - frontend

networks:
  demo_deploy:
    external: true
